
server:
  port: 8888

spring:
  datasource:
    url: jdbc:oracle:thin:@100.72.227.1:1521:FREE
    username: lab1
    password: lab1
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
  redis:
    host: 100.72.227.1
    port: 6379